// SPDX-License-Identifier: Apache-2.0
/**
 * curve.test.mjs — the on-curve test, pinned against things that are not this
 * implementation.
 *
 * A predicate that removes 85% of a distribution rests entirely on this
 * function. Testing it against itself would be worthless, so it is tested
 * against (a) ed25519 keys generated by Node's own crypto, which are on the
 * curve by construction, (b) addresses derived by Solana's own
 * `find_program_address` rule, which are off the curve by construction, (c)
 * real mainnet addresses of both kinds, and (d) the other copy of this code in
 * the same monorepo, whenever it is present.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { generateKeyPairSync, createHash } from 'node:crypto';
import { isOnCurve, pubkeyOnCurve } from './curve.mjs';
import { b58encode, b58decode } from './base58.mjs';

/** The raw 32 bytes of a freshly generated ed25519 public key. */
function realPublicKey() {
  const { publicKey } = generateKeyPairSync('ed25519');
  const der = publicKey.export({ format: 'der', type: 'spki' });
  return Uint8Array.from(der.subarray(der.length - 32));
}

test('every real ed25519 public key is on the curve', () => {
  for (let i = 0; i < 250; i++) {
    const raw = realPublicKey();
    assert.equal(isOnCurve(raw), true, `generated key ${i} reported off-curve: ${b58encode(raw)}`);
    assert.equal(pubkeyOnCurve(b58encode(raw)), true);
  }
});

test('a program-derived address is off the curve, by the same rule Solana uses', () => {
  // Solana's createProgramAddress: sha256(seeds || program_id || "ProgramDerivedAddress"),
  // rejected if it lands ON the curve. findProgramAddress walks the bump down
  // from 255 until it does not. So: run that walk, and the address it settles on
  // must be off-curve, 1000 times over, for independently chosen program ids.
  const marker = Buffer.from('ProgramDerivedAddress', 'utf8');
  let found = 0;
  for (let i = 0; i < 1000; i++) {
    const programId = Buffer.from(createHash('sha256').update(`program-${i}`).digest());
    const seed = Buffer.from(`seed-${i}`, 'utf8');
    for (let bump = 255; bump >= 0; bump--) {
      const h = Uint8Array.from(createHash('sha256')
        .update(Buffer.concat([seed, Buffer.from([bump]), programId, marker])).digest());
      if (!isOnCurve(h)) { found++; break; }
    }
  }
  assert.equal(found, 1000, 'every seed must yield some off-curve bump');
});

test('roughly half of arbitrary 32-byte values are on the curve', () => {
  // Not a property of our code so much as a sanity check that the test is
  // testing anything: if isOnCurve returned a constant, everything above would
  // still pass one of its two halves.
  let on = 0;
  for (let i = 0; i < 2000; i++) {
    if (isOnCurve(Uint8Array.from(createHash('sha256').update(`x${i}`).digest()))) on++;
  }
  assert.ok(on > 800 && on < 1200, `expected ~1000 of 2000 on-curve, got ${on}`);
});

test('known mainnet addresses land on the side they must', () => {
  // On-curve: ordinary wallets that appeared as owners in the demonstration run.
  for (const a of [
    '6Jtc91o51YXUzezsC8ZLaqYYfh3aPWJQBvfzwYea7jUo',
    'D93hBBFx39pEBxdAR3AzRsiZsN2J1pJk9W6PuXxADw5v',
    'CpZLVv63mUSRruto9RtciDumV3GAahUJrbDffRokTvUU',
  ]) assert.equal(pubkeyOnCurve(a), true, `${a} should be on-curve`);

  // Off-curve: the two pool authorities the predicate removes. The first is the
  // pump.fun AMM pool holding 85% of the demonstration distribution.
  for (const a of [
    'HgpbxqtHN8uuntiPsmpMGzJUhYLFfpC1H24M5phdYomL',
    'AiJncJexFGbpTa3y8jkuzVLXUMuAyf88VZYPmUqz42ue',
  ]) assert.equal(pubkeyOnCurve(a), false, `${a} should be off-curve`);

  // The all-zero pubkey — the System Program, and this project's placeholder
  // config — IS on the curve. Worth pinning: "looks like a special address" is
  // not the same fact as "off the curve", and a reader may assume it is.
  assert.equal(pubkeyOnCurve('11111111111111111111111111111111'), true);
});

test('a value that is not a 32-byte address is null, not false', () => {
  // The distinction matters: `false` means "off the curve, exclude it", and
  // silently returning that for a malformed owner would exclude an address on
  // the strength of a parse failure. `null` is what makes the predicate refuse.
  for (const bad of ['', 'not base58!', '0O0O0O', b58encode(new Uint8Array(31)), b58encode(new Uint8Array(33)), null, undefined]) {
    assert.equal(pubkeyOnCurve(bad), null, `${JSON.stringify(bad)} should be undecidable`);
  }
  assert.equal(isOnCurve(new Uint8Array(31)), false);
  assert.equal(isOnCurve(null), false);
});

test('the copy in ops/src/census agrees, wherever both are present', async (t) => {
  // `curve.mjs` is a deliberate copy so that indexer/ is independently
  // publishable. A copy that can drift silently is worse than an import, so
  // this pins them together in the monorepo and skips in the published repo.
  const other = new URL('../../ops/src/census/crypto.mjs', import.meta.url);
  if (!existsSync(other)) {
    t.skip('ops/src/census/crypto.mjs is not in this checkout (expected in the standalone repository)');
    return;
  }
  const ops = await import(other.href);
  for (let i = 0; i < 500; i++) {
    const bytes = Uint8Array.from(createHash('sha256').update(`agree-${i}`).digest());
    assert.equal(isOnCurve(bytes), ops.isOnCurve(bytes), `disagreement at i=${i}: ${b58encode(bytes)}`);
  }
  for (let i = 0; i < 50; i++) {
    const raw = realPublicKey();
    assert.equal(isOnCurve(raw), ops.isOnCurve(raw));
  }
  // And the base58 decoders they each depend on must agree too, or the
  // agreement above is about different bytes.
  for (const a of ['11111111111111111111111111111111', 'HgpbxqtHN8uuntiPsmpMGzJUhYLFfpC1H24M5phdYomL']) {
    assert.deepEqual([...b58decode(a)], [...ops.b58decode(a)]);
  }
});
